spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: account
graphql:
  servlet:
    tracing-enabled: true
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0